### YamlMime:ModuleUnit
uid: learn.wwl.implement-azure-cosmos-db-sql-api-point-operations.configure-ttl-for-document
title: Configure time-to-live (TTL) value for a specific document
metadata:
  title: Configure time-to-live (TTL) value for a specific document
  description: "Configure time-to-live (TTL) value for a specific document"
  ms.date: 10/22/2024
  author: wwlpublish
  ms.author: calopez
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 2
content: |
  [!include[](includes/6-configure-ttl-for-document.md)]
